version: "2"
services:

  app:
    image: members/app
    build: app
    container_name: members.test
    restart: always
    environment:
      DATABASE_URL: postgresql://app:password@db:5432/app?schema=public&connect_timeout=300
    volumes:
      - ./app/node_modules:/app/node_modules
      - ./app:/app

  db:
    # Choosing Aurora PostgreSQL compatible version.
    image: postgres:13.4-alpine3.14
    container_name: db.members.test
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    volumes:
      - ./datastores/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  proxy:
    image: members/proxy
    build: proxy
    container_name: proxy.members.test
    ports:
      - "80:80"
      - "443:443"
